server:
  port: 7077

spring:  application:    name: ms-registry

eureka:  instance:    hostname: eureka.registry
    instance-id: ${eureka.instance.hostname}
  client:#    register-with-eureka: false
#    fetch-registry: false
    service-url:      defaultZone: http://eureka.registry2:7078/eureka/

