server:
  port: 9077

spring:  application:    name: "ms-consumer"

eureka:
  client:
    service-url:
      defaultZone: http://eureka.registry:7077/eureka/,http://eureka.registry2:7078/eureka/
  instance:
    instance-id: id-of-ms-consumer
    prefer-ip-address: true

feign:  hystrix:    enabled: true

management:  endpoints:    web:      exposure:        include: "*"